### ISSUE TITLE
Needs to show fabrikamb2c configuration

### ISSUE THREAD

**Issue by Spawnkid** [Azure-Samples/active-directory-b2c-dotnet-uwp#1]
Please share your Azure B2C setup configuration (screenshot is much preferable) of your fabrikamb2c.

I was struggling to replicate this sample using my own B2C but I had no luck getting with signup.

- I did create/add a B2C application via the B2C blade (Azure AD B2C).
- Replaced the value of ClientId variable in the sample code by my own Application ID that I created earlier.
- Replaced the value of Tenant variable in the sample code by my own Domain name/Resource name.
- Created a PolicySignUpSignIn,PolicyEditProfile and PolicyResetPassword using default values (in susi policy, the claims are just Email Addresses,Identity Provider and User is new). Then  replaced the value of their respective variables in the app.
- I also created a custom redirecturi based on ms doc recommendation "com.onmicrosoft.domain.app://redirect/" (though I tried to use the two default redirecturi [urn:ietf:wg:oauth:2.0:oob,https://login.microsoftonline.com/tfp/oauth2/nativeclient], it still doesn't work) 

Then run the app, perform a signup, waited for the code sent in the email, after validation I entered a strong password then sent.... AND screen shows

**We can' connect to the service right now. Check your network connection or try again later.**

Network issue? nope. I stop the app. revert the entire app.cs from orig file then run again. This time using fabrikamb2c setup, did a signup..suprise! it works. So what did I do wrong?

**Comment by parakhj** [comment]
Sounds like everything should work. Did you update the redirect URI in your app?

**Comment by Dark-Bond** [comment]
I am having the same problem.  The issue appears to be that there is absolutely no documentation describing how to set up the API Scopes.  This apparently is a new feature of the API and there is virtually nothing written about it.  The instructions for setting up the application reference this document:
https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-app-registration#register-a-mobilenative-application
Which give ABSOLUTELY NO guidance on how to set up the API scopes.  I was able to figure out that if you make the slightest change to the API Scope in the example, you're able to sign in, but get a NULL access token.

**Comment by jhhouston** [comment]
The demo works but implementing into my application triggers and error.

Error message CS0619  app.xaml.cs line 115:
public static PublicClientApplication PublicClientApp { get; } = new PublicClientApplication(ClientId, Authority);

Error Description:
'PublicClientApplication.PublicClientApplication(string, string)' is obsolete: 'Use PublicClientApplicationBuilder instead.

I have read the documentation: https://aka.ms/msal-net-3-breaking-changes . Not sure how to implement it all attempts have failed. Thanks

**Comment by jmprieur** [comment]
This should be fixed.
