### ISSUE TITLE
Window_Loaded event handler never hooked up

### ISSUE THREAD

**Issue by HappyNomad** [Azure-Samples/active-directory-b2c-dotnet-uwp#7]
This sample was apparently copied from the WPF one with few changes.  Whereas the WPF one hooks up Window_Loaded, this one doesn't.  I think that's an oversight that occurred while porting the code.

On another note, I couldn't get this sample to run as is.  I had to create a brand new UWP project in VS, and then copy the significant files over.  Perhaps you want to do the same for what's hosted here.

**Comment by jmprieur** [comment]
I just proposed a PR:https://github.com/Azure-Samples/active-directory-b2c-dotnet-uwp/pull/9

**Comment by ChainReactive** [comment]
@jmprieur @jennyf19 Hi, I'm confused.  The problems mentioned in this issue weren't addressed by the PR, yet you closed the issue?

Window_Loaded is still not hooked up and when I download and open the project in Visual Studio, I still cannot run it as is.  It still only shows "Device" as the run option which I cannot get to work.

**Comment by jennyf19** [comment]
@ChainReactive sorry...i did not look at the issue, just the PR. will take a look, but might not be until next week. 
@bgavrilMS - fyi, in case you have time.

**Comment by bgavrilMS** [comment]
Please use WinUI. UWP is not being invested in.
