### ISSUE TITLE
PublicClientApplication is Obsolete

### ISSUE THREAD

**Issue by jhhouston** [Azure-Samples/active-directory-b2c-dotnet-uwp#8]
The demo works but implementing into my application triggers and error.

Error message CS0619 app.xaml.cs line 115:
public static PublicClientApplication PublicClientApp { get; } = new PublicClientApplication(ClientId, Authority);

Error Description:
'PublicClientApplication.PublicClientApplication(string, string)' is obsolete: 'Use PublicClientApplicationBuilder instead.

I have read the documentation: https://aka.ms/msal-net-3-breaking-changes . Not sure how to implement it all attempts have failed. Thanks

**Comment by jmprieur** [comment]
@jhhouston 
I've provided a PR to migrate to MSAL.NET 4.0:
https://github.com/Azure-Samples/active-directory-b2c-dotnet-uwp/pull/9

**Comment by jhhouston** [comment]
Thank you
